// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {netstat} from '../models';

export function FetchPorts():Promise<Array<netstat.SockTabEntry>>;

export function Greet(arg1:string):Promise<string>;
