// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {netstat} from '../models';

export function FetchPorts(arg1:number,arg2:number):Promise<Array<netstat.SockTabEntry>>;
