// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchPorts(arg1, arg2) {
  return window['go']['main']['App']['FetchPorts'](arg1, arg2);
}

export function KillProcess(arg1, arg2, arg3) {
  return window['go']['main']['App']['KillProcess'](arg1, arg2, arg3);
}
